doc:
    _id: _design/juggler

load:
- rewrites.yml
- filters.yml

externals:
- name: underscore
  url: http://underscorejs.org/underscore.js
- name: underscore
  url: http://underscorejs.org/underscore.js
  attachment: js/vendor/underscore.js


attachments:
- index.html


